- name: app setup
  import_role:
    name: common
    tasks_from: app-setup
- name: systemd setup
  import_role:
    name: common
    tasks_from: systemd-setup
- name: python setup
  import_role:
    name: common
    tasks_from: python
- name: move shipping jar
  command: mv target/shipping-1.0.jar shipping.jar 
  args:
    chdir: /app
- name: load mysql data
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root
    login_password: RoboShop@1
    login_host: "{{ MYSQL_HOST }}"
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql 
- name: restart and enable shipping
  service:
    name: shipping
    state: restarted
    enabled: yes  