[local]
localhost

[mongodb]
mongodb.anu90.shop

[redis]
redis.anu90.shop

[mysql]
mysql.anu90.shop

[rabbitmq]
rabbitmq.anu90.shop

[catalogue]
catalogue.anu90.shop

[rabbitmq]
rabbitmq.anu90.shop

[user]
user.anu90.shop

[cart]
cart.anu90.shop

[shipping]
shipping.anu90.shop

[payment]
payment.anu90.shop

[frontend]
frontend.anu90.shop